[env:spectre_node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps = 
    jgromes/RadioLib @ ^6.1.0
    bxparks/AceButton @ ^1.9.2
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit SH110X @ ^2.1.8
    adafruit/Adafruit BusIO @ ^1.14.5

build_flags = 
    -D MBEDTLS_GCM_C
    -D MBEDTLS_ECDH_C
    -D MBEDTLS_ECP_DP_SECP256R1_ENABLED