// =============================================================================
// S.P.E.C.T.R.E. - Secure Portable Encrypted Communication Terminal
//                  for Remote Environments
//
// Hardware : ESP32 (dual-core) + SX1278 Ra-02 LoRa module
// Libraries: RadioLib, TFT_eSPI, AceButton, mbedTLS (bundled in ESP-IDF)
// RTOS     : FreeRTOS (shipped with Arduino-ESP32 core)
//
// Pin Map (adjust to your wiring):
//   LoRa SX1278 --> ESP32
//     NSS  --> GPIO 5
//     DIO0 --> GPIO 26  (RX-done / TX-done interrupt)
//                        *** GPIO 2 is a boot strapping pin on the ESP32 DevKit V1.
//                            If the Ra-02 pulls it HIGH at power-on, the chip will
//                            refuse to boot. GPIO 26 is a safe, interrupt-capable
//                            alternative with no strapping function. ***
//     RESET--> GPIO 14
//     MOSI --> GPIO 23  (VSPI)
//     MISO --> GPIO 19
//     SCK  --> GPIO 18
//
//   TFT (TFT_eSPI – configure User_Setup.h in the library):
//     Uses its own SPI bus or shared VSPI – defined in library config.
//
//   Buttons (AceButton):
//     BTN_UP   --> GPIO 32
//     BTN_DOWN --> GPIO 33
//     BTN_SEL  --> GPIO 25
//
// Build flags (platformio.ini example):
//   build_flags =
//     -DCORE_DEBUG_LEVEL=3
//     -DRADIOLIB_GODMODE          ; optional – exposes all RadioLib internals
// =============================================================================

#include <Arduino.h>
#include <RadioLib.h>          // LoRa driver  (install via PlatformIO / Library Manager)
#include <TFT_eSPI.h>          // Display driver (configure User_Setup.h)
#include <AceButton.h>         // Debounced button handling
#include "mbedtls/gcm.h"       // AES-GCM (Authenticated Encryption)

using namespace ace_button;

// =============================================================================
// COMPILE-TIME CONFIGURATION
// =============================================================================

// LoRa RF parameters – tune for your region / link budget
#define LORA_FREQUENCY      433.0   // MHz  (433 for Ra-02; 868/915 for other modules)
#define LORA_BANDWIDTH      125.0   // kHz
#define LORA_SF             10      // Spreading Factor 7-12 (higher = longer range, slower)
#define LORA_CR             6       // Coding Rate denominator (5-8)
#define LORA_SYNC_WORD      0x34    // Private network sync word (not 0x12 public)
#define LORA_TX_POWER       17      // dBm

// SPI / GPIO
#define LORA_NSS_PIN        5
#define LORA_DIO0_PIN       26  // Safe interrupt pin – GPIO 2 is a strapping pin, never use it for DIO0
#define LORA_RESET_PIN      14
#define LORA_DIO1_PIN       RADIOLIB_NC

// Buttons
#define BTN_UP_PIN          32
#define BTN_DOWN_PIN        33
#define BTN_SEL_PIN         25

// AES-256 requires a 32-byte key and 16-byte IV.
// *** REPLACE WITH YOUR SHARED SECRET – never ship with these defaults ***
static const uint8_t AES_KEY[32] = {
    0x53,0x50,0x45,0x43,0x54,0x52,0x45,0x5F,   // "SPECTRE_"
    0x53,0x45,0x43,0x55,0x52,0x45,0x5F,0x4B,   // "SECURE_K"
    0x45,0x59,0x5F,0x44,0x45,0x56,0x5F,0x4F,   // "EY_DEV_O"
    0x4E,0x4C,0x59,0x5F,0x30,0x30,0x30,0x31    // "NLY_0001"
};
// No static IV – a fresh 16-byte IV is generated by esp_fill_random() for every
// transmission and prepended to the LoRaPacket so the receiver can decrypt it.
// Using a static IV with CBC would produce identical ciphertexts for identical
// messages, enabling replay attacks and pattern recognition by an adversary.

// Mesh / packet settings
#define MAX_PAYLOAD_LEN     128     // bytes (plaintext and ciphertext are same length)

// RTOS queue depths
#define QUEUE_DEPTH         5

// =============================================================================
// DATA STRUCTURES
// =============================================================================

struct MessageEvent {
    uint8_t  messageID;                 // Predefined message type (1=Mayday, 2=Extract, etc.)
    uint8_t  hopCount;                  // For Store-and-Forward mesh (max hops before drop)
    char     payload[MAX_PAYLOAD_LEN];  // Plaintext (TX path) or decrypted text (RX path)
};

// Mesh packet transmitted over the air
struct __attribute__((packed)) LoRaPacket {
    uint8_t  magicByte;                         // 0xAB = valid S.P.E.C.T.R.E. packet
    uint8_t  messageID;
    uint8_t  hopCount;
    uint8_t  payloadLen;                        // Length of the encrypted blob
    uint8_t  iv[12];                            // 12-byte random nonce for AES-GCM
    uint8_t  tag[16];                           // 16-byte authentication tag
    uint8_t  encrypted[MAX_PAYLOAD_LEN];        // AES-256-GCM ciphertext (no padding)
};

// =============================================================================
// GLOBAL HANDLES
// =============================================================================

QueueHandle_t txQueue;          // UI/Input  --> Radio task
QueueHandle_t rxQueue;          // Radio     --> UI task

TaskHandle_t  taskRadioHandle;
TaskHandle_t  taskUIHandle;
TaskHandle_t  taskInputHandle;

// RadioLib objects
SX1278 radio = new Module(LORA_NSS_PIN, LORA_DIO0_PIN, LORA_RESET_PIN, LORA_DIO1_PIN);

// Display
TFT_eSPI tft = TFT_eSPI();

// Buttons (AceButton)
AceButton btnUp(BTN_UP_PIN);
AceButton btnDown(BTN_DOWN_PIN);
AceButton btnSel(BTN_SEL_PIN);

// Volatile flag set by RadioLib's DIO0 ISR
volatile bool rxFlag = false;

// =============================================================================
// MENU STATE (shared only by UI task – no mutex needed as it's single-writer)
// =============================================================================

enum MenuState { MENU_MAIN, MENU_INBOX, MENU_COMPOSE };

static MenuState currentMenu    = MENU_MAIN;
static int       menuCursor     = 0;
static const char* menuItems[]  = { "1. Mayday!", "2. Extract", "3. Regroup", "4. Sitrep", "5. Inbox" };
static const int   menuCount    = 5;

// Predefined tactical messages
static const char* tacMessages[] = {
    "MAYDAY! Sector 4. Immediate assistance required.",
    "Extraction requested at primary LZ. Awaiting confirmation.",
    "All units regroup at Checkpoint Bravo.",
    "Status nominal. Holding position. No enemy contact."
};

// =============================================================================
// CRYPTOGRAPHIC HELPERS  (Core 0 – Radio task only)
// =============================================================================

/**
 * @brief  Encrypt plaintext with AES-256-GCM.
 * @param  plaintext  Input buffer (null-terminated string)
 * @param  iv         12-byte IV (nonce) generated fresh for this message.
 * @param  ciphertext Output buffer (must be >= payload length)
 * @param  tag        16-byte authentication tag output buffer
 * @return Length of ciphertext in bytes.
 */
static int aes256Encrypt(const char* plaintext, const uint8_t* iv, uint8_t* ciphertext, uint8_t* tag) {
    mbedtls_gcm_context ctx;
    mbedtls_gcm_init(&ctx);
    mbedtls_gcm_setkey(&ctx, MBEDTLS_CIPHER_ID_AES, AES_KEY, 256);

    size_t textLen = strnlen(plaintext, MAX_PAYLOAD_LEN - 1);

    mbedtls_gcm_crypt_and_tag(&ctx, MBEDTLS_GCM_ENCRYPT, textLen,
                              iv, 12,
                              NULL, 0, // No additional authenticated data (AAD)
                              (const unsigned char*)plaintext, ciphertext,
                              16, tag);

    mbedtls_gcm_free(&ctx);
    return (int)textLen;
}

/**
 * @brief  Decrypt and authenticate AES-256-GCM ciphertext.
 * @param  ciphertext  Encrypted buffer
 * @param  len         Length of ciphertext
 * @param  iv          12-byte IV read from the packet header
 * @param  tag         16-byte authentication tag read from the packet header
 * @param  plaintext   Output buffer
 * @return true if authentication succeeded, false otherwise.
 */
static bool aes256Decrypt(const uint8_t* ciphertext, int len, const uint8_t* iv, const uint8_t* tag, char* plaintext) {
    mbedtls_gcm_context ctx;
    mbedtls_gcm_init(&ctx);
    mbedtls_gcm_setkey(&ctx, MBEDTLS_CIPHER_ID_AES, AES_KEY, 256);

    int ret = mbedtls_gcm_auth_decrypt(&ctx, len,
                                       iv, 12,
                                       NULL, 0, // No AAD
                                       tag, 16,
                                       ciphertext, (unsigned char*)plaintext);

    mbedtls_gcm_free(&ctx);

    if (ret == 0) {
        plaintext[len] = '\0';
        return true;
    }
    return false;
}

// =============================================================================
// DIO0 INTERRUPT SERVICE ROUTINE  (keep minimal – just set a flag)
// =============================================================================
void IRAM_ATTR onDio0Rise() {
    rxFlag = true;
}

// =============================================================================
// CORE 0: RADIO & CRYPTO TASK  – "The Vault"
// =============================================================================
void taskRadioAndCrypto(void* pvParameters) {
    Serial.printf("[Radio] Task started on Core %d\n", xPortGetCoreID());

    // ----- RadioLib initialisation -----
    int state = radio.begin(
        LORA_FREQUENCY,
        LORA_BANDWIDTH,
        LORA_SF,
        LORA_CR,
        LORA_SYNC_WORD,
        LORA_TX_POWER
    );

    if (state != RADIOLIB_ERR_NONE) {
        Serial.printf("[Radio] FATAL: LoRa init failed, code %d\n", state);
        // Signal the UI task to show an error, then suspend self
        MessageEvent errMsg;
        errMsg.messageID = 0xFF;
        snprintf(errMsg.payload, MAX_PAYLOAD_LEN, "LoRa INIT FAIL! Code: %d", state);
        xQueueSend(rxQueue, &errMsg, portMAX_DELAY);
        vTaskSuspend(NULL);
    }
    Serial.println("[Radio] LoRa initialised OK.");

    // Attach DIO0 interrupt for RX-done detection
    attachInterrupt(digitalPinToInterrupt(LORA_DIO0_PIN), onDio0Rise, RISING);

    // Start in continuous receive mode
    radio.startReceive();

    LoRaPacket  pkt;
    MessageEvent outMsg, inMsg;

    for (;;) {
        // ------------------------------------------------------------------
        // 1. TX PATH: Check if the UI has queued a message to transmit
        // ------------------------------------------------------------------
        if (xQueueReceive(txQueue, &outMsg, 0) == pdPASS) {
            Serial.printf("[Radio][TX] Encrypting message ID %u: \"%s\"\n",
                          outMsg.messageID, outMsg.payload);

            memset(&pkt, 0, sizeof(pkt));
            pkt.magicByte  = 0xAB;
            pkt.messageID  = outMsg.messageID;
            pkt.hopCount   = outMsg.hopCount;

            // Generate a fresh random 12-byte IV for this message.
            esp_fill_random(pkt.iv, 12);

            int cLen = aes256Encrypt(outMsg.payload, pkt.iv, pkt.encrypted, pkt.tag);
            pkt.payloadLen = (uint8_t)cLen;

            // Stop listening while we transmit
            radio.standby();

            // Calculate size dynamically since payload isn't padded
            size_t pktSize = sizeof(LoRaPacket) - MAX_PAYLOAD_LEN + cLen;
            state = radio.transmit((uint8_t*)&pkt, pktSize);

            if (state == RADIOLIB_ERR_NONE) {
                Serial.printf("[Radio][TX] Transmitted %u bytes OK.\n", pktSize);
            } else {
                Serial.printf("[Radio][TX] Transmit failed, code %d\n", state);
            }

            // Return to continuous receive
            rxFlag = false;
            radio.startReceive();
        }

        // ------------------------------------------------------------------
        // 2. RX PATH: DIO0 ISR set the flag – read the packet
        // ------------------------------------------------------------------
        if (rxFlag) {
            rxFlag = false;

            uint8_t buf[sizeof(LoRaPacket)];
            size_t  rxLen = sizeof(buf);
            state = radio.readData(buf, rxLen);

            if (state == RADIOLIB_ERR_NONE) {
                LoRaPacket* rxPkt = (LoRaPacket*)buf;

                if (rxPkt->magicByte != 0xAB) {
                    Serial.println("[Radio][RX] Ignored: bad magic byte.");
                } else {
                    Serial.printf("[Radio][RX] Packet from air – RSSI: %.1f dBm, SNR: %.1f dB\n",
                                  radio.getRSSI(), radio.getSNR());

                    memset(&inMsg, 0, sizeof(inMsg));
                    inMsg.messageID = rxPkt->messageID;
                    inMsg.hopCount  = rxPkt->hopCount;
                    
                    bool authOk = aes256Decrypt(rxPkt->encrypted, rxPkt->payloadLen, rxPkt->iv, rxPkt->tag, inMsg.payload);

                    if (authOk) {
                        Serial.printf("[Radio][RX] Decrypted: \"%s\"\n", inMsg.payload);

                        // Push to UI task
                        xQueueSend(rxQueue, &inMsg, 0);

                        // ----------------------------------------------------------
                        // STORE-AND-FORWARD MESH RELAY LOGIC
                        // ----------------------------------------------------------
                        if (rxPkt->hopCount > 0) {
                            rxPkt->hopCount--;
                            radio.standby();
                            vTaskDelay((esp_random() % 200 + 50) / portTICK_PERIOD_MS);
                            size_t relaySize = sizeof(LoRaPacket) - MAX_PAYLOAD_LEN + rxPkt->payloadLen;
                            radio.transmit(buf, relaySize);
                            Serial.printf("[Radio][MESH] Relayed packet (hops left: %u)\n",
                                          rxPkt->hopCount);
                            rxFlag = false;
                            radio.startReceive();
                        }
                    } else {
                        Serial.println("[Radio][RX] Authentication failed. Packet modified or wrong key!");
                    }
                }
            } else if (state == RADIOLIB_ERR_CRC_MISMATCH) {
                Serial.println("[Radio][RX] CRC mismatch – packet corrupted.");
            } else {
                Serial.printf("[Radio][RX] Read error, code %d\n", state);
            }
        }

        vTaskDelay(20 / portTICK_PERIOD_MS);    // Yield to watchdog
    }
}

// =============================================================================
// DISPLAY HELPERS  (called only from Core 1 / UI task)
// =============================================================================

static void drawMainMenu() {
    tft.fillScreen(TFT_BLACK);
    tft.setTextColor(TFT_GREEN, TFT_BLACK);
    tft.setTextSize(1);
    tft.drawString("== S.P.E.C.T.R.E. ==", 5, 2);
    tft.drawFastHLine(0, 12, tft.width(), TFT_GREEN);

    for (int i = 0; i < menuCount; i++) {
        if (i == menuCursor) {
            tft.setTextColor(TFT_BLACK, TFT_GREEN);
        } else {
            tft.setTextColor(TFT_GREEN, TFT_BLACK);
        }
        tft.drawString(menuItems[i], 5, 18 + i * 14);
    }
}

static void drawInbox(const MessageEvent& msg) {
    tft.fillScreen(TFT_BLACK);
    tft.setTextColor(TFT_CYAN, TFT_BLACK);
    tft.drawString("== INBOX ==", 5, 2);
    tft.drawFastHLine(0, 12, tft.width(), TFT_CYAN);
    tft.setTextColor(TFT_WHITE, TFT_BLACK);
    tft.setTextWrap(true);
    tft.drawString(msg.payload, 5, 20);
    tft.setTextColor(TFT_YELLOW, TFT_BLACK);
    char rssiStr[32];
    snprintf(rssiStr, sizeof(rssiStr), "MsgID:%u Hops:%u", msg.messageID, msg.hopCount);
    tft.drawString(rssiStr, 5, tft.height() - 14);
}

static void drawBootScreen() {
    tft.fillScreen(TFT_BLACK);
    tft.setTextColor(TFT_GREEN, TFT_BLACK);
    tft.setTextSize(2);
    tft.drawString("SPECTRE OS", 10, 20);
    tft.setTextSize(1);
    tft.setTextColor(TFT_WHITE, TFT_BLACK);
    tft.drawString("BOOTING...", 10, 55);
    tft.drawString("Running BIST", 10, 70);
}

// State shared between Input callback and UI task.
// Declared here – above taskUI – so the compiler sees them before their first
// use in taskUI. Declaring them below taskUI (next to handleButtonEvent) caused
// a fatal "identifier not found" error at the if (menuChanged) check in taskUI.
// Marked volatile so the compiler never caches them in a register across tasks.
static volatile bool      needRedraw  = false;  // UI task polls this to know when to repaint
static volatile MenuState nextMenu    = MENU_MAIN;
static volatile bool      menuChanged = false;  // True when nextMenu has been updated

// =============================================================================
// CORE 1: USER INTERFACE TASK  – "The Display"
//
// This is the SOLE owner of the TFT SPI bus.  No other task or callback may
// call tft.* functions.  It consumes the needRedraw / menuChanged flags that
// the Input callback sets, then executes the actual draw calls safely.
// =============================================================================
void taskUI(void* pvParameters) {
    Serial.printf("[UI] Task started on Core %d\n", xPortGetCoreID());

    tft.init();
    tft.setRotation(1);
    tft.fillScreen(TFT_BLACK);

    drawBootScreen();
    vTaskDelay(2000 / portTICK_PERIOD_MS);

    currentMenu = MENU_MAIN;
    drawMainMenu();

    MessageEvent inMsg;

    for (;;) {
        // ------------------------------------------------------------------
        // 1. Apply any menu/state transition requested by the Input callback
        // ------------------------------------------------------------------
        if (menuChanged) {
            menuChanged = false;            // Clear flag first to avoid missing a
                                            // subsequent event during the draw call
            currentMenu = (MenuState)nextMenu;

            switch (currentMenu) {
                case MENU_MAIN:
                    drawMainMenu();
                    break;

                case MENU_INBOX:
                    tft.fillScreen(TFT_BLACK);
                    tft.setTextColor(TFT_CYAN, TFT_BLACK);
                    tft.drawString("== INBOX ==", 5, 2);
                    tft.drawFastHLine(0, 12, tft.width(), TFT_CYAN);
                    tft.setTextColor(TFT_WHITE, TFT_BLACK);
                    tft.drawString("Awaiting messages...", 5, 30);
                    break;

                case MENU_COMPOSE:
                    // Used as the "TX Sent" confirmation screen
                    tft.fillScreen(TFT_BLACK);
                    tft.setTextColor(TFT_YELLOW, TFT_BLACK);
                    tft.drawString("[ TRANSMITTING ]", 5, 30);
                    tft.setTextColor(TFT_WHITE, TFT_BLACK);
                    tft.drawString(tacMessages[menuCursor], 5, 50);
                    // Return to main after a brief visual hold
                    vTaskDelay(800 / portTICK_PERIOD_MS);
                    currentMenu = MENU_MAIN;
                    drawMainMenu();
                    break;
            }
        }

        // ------------------------------------------------------------------
        // 2. Repaint main menu if the cursor moved (UP/DOWN button)
        // ------------------------------------------------------------------
        if (needRedraw) {
            needRedraw = false;
            if (currentMenu == MENU_MAIN) {
                drawMainMenu();
            }
        }

        // ------------------------------------------------------------------
        // 3. Check if Radio received a new over-the-air message
        // ------------------------------------------------------------------
        if (xQueueReceive(rxQueue, &inMsg, 0) == pdPASS) {
            if (inMsg.messageID == 0xFF) {
                tft.fillScreen(TFT_RED);
                tft.setTextColor(TFT_WHITE, TFT_RED);
                tft.drawString("RADIO ERROR!", 5, 20);
                tft.drawString(inMsg.payload, 5, 40);
            } else {
                drawInbox(inMsg);
                currentMenu = MENU_INBOX;
            }
        }

        vTaskDelay(20 / portTICK_PERIOD_MS);    // ~50 fps budget
    }
}

// =============================================================================
// BUTTON EVENT HANDLER  (AceButton callback – called from taskInput, Core 1)
//
// *** SPI BUS OWNERSHIP RULE ***
// taskInput has priority 3; taskUI has priority 2.  On a button press, the
// RTOS will preempt taskUI mid-draw and run this callback.  If this function
// called any tft.* commands it would corrupt the in-progress SPI transaction,
// causing display static or a system freeze.
//
// Fix: this function ONLY updates shared state variables and sets the redraw
// flag.  taskUI reads that flag each cycle and is the ONLY place tft.* calls
// are ever made.
// =============================================================================

static void handleButtonEvent(AceButton* button, uint8_t eventType, uint8_t /*buttonState*/) {
    if (eventType != AceButton::kEventPressed) return;

    uint8_t pin = button->getPin();

    if (currentMenu == MENU_MAIN) {
        if (pin == BTN_UP_PIN) {
            menuCursor = (menuCursor - 1 + menuCount) % menuCount;
            needRedraw = true;                      // Ask UI task to repaint – no tft call here
        } else if (pin == BTN_DOWN_PIN) {
            menuCursor = (menuCursor + 1) % menuCount;
            needRedraw = true;
        } else if (pin == BTN_SEL_PIN) {
            if (menuCursor == menuCount - 1) {
                // "Inbox" item selected
                nextMenu    = MENU_INBOX;
                menuChanged = true;
            } else {
                // Queue a predefined tactical TX message
                MessageEvent txMsg;
                txMsg.messageID = (uint8_t)(menuCursor + 1);
                txMsg.hopCount  = 3;
                strncpy(txMsg.payload, tacMessages[menuCursor], MAX_PAYLOAD_LEN - 1);
                txMsg.payload[MAX_PAYLOAD_LEN - 1] = '\0';

                Serial.printf("[Input] Queuing TX: \"%s\"\n", txMsg.payload);
                // xQueueSend is ISR-safe when called from a task context
                xQueueSend(txQueue, &txMsg, 0);

                // Signal UI task to show the TX-confirmation screen
                nextMenu    = MENU_COMPOSE;     // Re-use COMPOSE state as "TX pending" view
                menuChanged = true;
            }
        }
    } else if (currentMenu == MENU_INBOX || currentMenu == MENU_COMPOSE) {
        // Any button press from non-main screens returns to main menu
        nextMenu    = MENU_MAIN;
        menuChanged = true;
    }
}

// =============================================================================
// CORE 1: INPUT TASK  – "The Buttons"
// =============================================================================
void taskInput(void* pvParameters) {
    Serial.printf("[Input] Task started on Core %d\n", xPortGetCoreID());

    // Configure button pins
    pinMode(BTN_UP_PIN,   INPUT_PULLUP);
    pinMode(BTN_DOWN_PIN, INPUT_PULLUP);
    pinMode(BTN_SEL_PIN,  INPUT_PULLUP);

    // Register AceButton event handler
    ButtonConfig* config = ButtonConfig::getSystemButtonConfig();
    config->setEventHandler(handleButtonEvent);
    config->setFeature(ButtonConfig::kFeatureClick);
    config->setFeature(ButtonConfig::kFeatureLongPress);

    for (;;) {
        btnUp.check();
        btnDown.check();
        btnSel.check();
        vTaskDelay(10 / portTICK_PERIOD_MS);    // AceButton needs ~10 ms polling
    }
}

// =============================================================================
// SETUP & LOOP
// =============================================================================
void setup() {
    Serial.begin(115200);
    vTaskDelay(1000 / portTICK_PERIOD_MS);
    Serial.println("\n==============================");
    Serial.println("  S.P.E.C.T.R.E. OS BOOTING");
    Serial.println("==============================");

    // Create inter-task queues
    txQueue = xQueueCreate(QUEUE_DEPTH, sizeof(MessageEvent));
    rxQueue = xQueueCreate(QUEUE_DEPTH, sizeof(MessageEvent));

    if (!txQueue || !rxQueue) {
        Serial.println("[FATAL] Queue creation failed – halting.");
        while (true) {}
    }

    // -------------------------------------------------------------------------
    // Launch RTOS tasks
    //
    // Core 0: Radio/Crypto  – highest priority (3) so RF deadlines are never missed
    // Core 1: UI            – medium priority  (2) keeps display responsive
    // Core 1: Input         – high priority    (3) so button events are not lost
    // -------------------------------------------------------------------------
    xTaskCreatePinnedToCore(taskRadioAndCrypto, "RadioTask",  8192, NULL, 3, &taskRadioHandle, 0);
    xTaskCreatePinnedToCore(taskUI,             "UITask",     6144, NULL, 2, &taskUIHandle,    1);
    xTaskCreatePinnedToCore(taskInput,          "InputTask",  4096, NULL, 3, &taskInputHandle, 1);

    Serial.println("[Setup] RTOS scheduler started.");
}

void loop() {
    // FreeRTOS owns the scheduler – loop() task is deleted to reclaim its stack.
    vTaskDelete(NULL);
}